version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HszGdZFpIKYEuPE3o4ru
    networks:
      - meuprojeto-network
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/MeuProjeto.API/Dockerfile
    container_name: meuprojeto-api
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - meuprojeto-network

networks:
  meuprojeto-network:

volumes:
  sql_data:
