version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=HszGdZFpIKYEuPE3o4ru
    networks:
      - meuprojeto-network
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: meu_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - meuprojeto-network

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin123456
    networks:
      - meuprojeto-network
    volumes:
      - seq_data:/data

  api:
    build:
      context: .
      dockerfile: src/MeuProjeto.API/Dockerfile
    container_name: meuprojeto-api
    depends_on:
      - sqlserver
      - rabbitmq
      - seq
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - meuprojeto-network

networks:
  meuprojeto-network:
    driver: bridge

volumes:
  sql_data:
  seq_data:
